version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: review_user
      POSTGRES_PASSWORD: review_pass
      POSTGRES_DB: review_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres-data:
    name: review-dashboard-postgres-data
